---
  - name: Apply CSS to half of a character
    hosts: localhost
    vars:
      character: "{{ character | default('X') }}"
      css_property: "{{ css_property | default('color') }}"
      css_value: "{{ css_value | default('red') }}"
      
    tasks:
      - name: Display half of the character
        debug:
          msg: "{{ character[:len(character)//2] }}"
          msg: "style='{{ css_property }}: {{ css_value }};'"
