answer: |-
  ---
  - name: Create an unordered list without any bullets
    hosts: localhost
    gather_facts: false

    tasks:
      - name: Set custom values
        set_fact:
          items:
            - "{{ item1 }}"
            - "{{ item2 }}"
            - "{{ item3 }}"
        
      - name: Print unordered list without bullets
        debug:
          msg: |
            {% for item in items %}
            - {{ item }}
            {% endfor %}
