answer: |-
  ---
  - name: Exclude a directory when using `find`
    hosts: localhost
    tasks:
      - name: Find files excluding a directory
        find:
          paths: "{{ search_path }}"
          patterns: "*"
          excludes: "{{ exclude_dir }}"
        register: found_files

      - name: Print found files
        debug:
          var: found_files.files
        when: found_files.matched > 0

    vars:
      search_path: "/path/to/search"
      exclude_dir: "exclude_directory"
