answer: |-
  - name: How to compare arrays in JavaScript
    hosts: localhost
    vars:
      array1: "{{ array1 }}"    
      array2: "{{ array2 }}"    

    tasks:
      - name: Compare arrays in JavaScript
        debug:
          msg: |
            var array1 = {{ array1 }};
            var array2 = {{ array2 }};

            function arraysEqual(arr1, arr2) {
              if (arr1.length !== arr2.length) return false;
              for (var i = 0; i < arr1.length; i++) {
                if (arr1[i] !== arr2[i]) return false;
              }
              return true;
            }

            var arraysAreEqual = arraysEqual(array1, array2);
            console.log(`Are the arrays equal? ${arraysAreEqual}`);
