|-
  ---
  - name: Why does the C preprocessor interpret the word "linux" as the constant "1"?
    hosts: localhost
    vars:
      custom_value: "{{ custom_value }}"
    tasks:
      - name: Explanation of C preprocessor behavior
        debug:
          msg: "The C preprocessor interprets the word 'linux' as the constant '1' because the preprocessor treats any non-zero value as true and 'linux' evaluates to 1 when converted to ASCII values."
        loop: "{{ custom_value.split(',') }}"
        loop_control:
          label: "{{ item }}"
