- name: Explanation of the !! operator in JavaScript
    hosts: localhost
    vars:
      custom_value: true # Replace with your desired custom value
      
    tasks:
      - name: Display the value of the !! operator
        debug:
          msg: "The value of the !! operator is {{ custom_value }}"
