---
- name: Setup Avail Validator Node
  hosts: all
  become: true
  vars:
    avail_version: "2.2.4.1"
    node_name: "my-node"
    chain_type: "mainnet"

  tasks:
    - name: Create Avail directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "/root/avail"
        - "/root/avail/node-data"

    - name: Download Avail binary
      ansible.builtin.get_url:
        url: "https://github.com/availproject/avail/releases/download/v{{ avail_version }}/x86_64-ubuntu-2204-avail-node.tar.gz"
        dest: "/root/avail/x86_64-ubuntu-2204-avail-node.tar.gz"
      register: download_result

    - name: Unpack Avail binary
      ansible.builtin.unarchive:
        src: "/root/avail/x86_64-ubuntu-2204-avail-node.tar.gz"
        dest: "/root/avail"
        remote_src: yes
      when: download_result is succeeded

    - name: Clean up downloaded tar file
      ansible.builtin.file:
        path: "/root/avail/x86_64-ubuntu-2204-avail-node.tar.gz"
        state: absent

    - name: Create systemd service file for Avail node
      ansible.builtin.copy:
        dest: /etc/systemd/system/avail.service
        content: |
          [Unit]
          Description=Avail Node

          [Service]
          Type=simple
          ExecStart=/root/avail/avail-node --chain {{ chain_type }} --name {{ node_name }} --validator -d /root/avail/node-data
          Restart=always
          RestartSec=3
          StandardOutput=syslog
          StandardError=syslog
          SyslogIdentifier=avail-node

          [Install]
          WantedBy=multi-user.target
        mode: '0644'

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: Start and enable Avail service
      ansible.builtin.systemd:
        name: avail.service
        state: started
        enabled: yes

