answer: |-
  ---
  - hosts: all
    become: true
    vars:
      node_version: "10.16.3"
    tasks:
      - name: Uninstall Node.js
        shell: |
          sudo apt-get remove nodejs -y
          sudo rm -rf /usr/local/lib/nodejs
        when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
        
      - name: Uninstall Node.js
        shell: |
          sudo yum remove nodejs -y
          sudo rm -rf /usr/local/lib/nodejs
        when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
