---
  - name: Ansible Playbook to demonstrate the use of ':-!!' in C
    hosts: localhost
    vars:
      custom_variable: "{{ custom_value }}"
    
    tasks:
      - name: Display the custom variable value
        debug:
          msg: "The custom variable value is {{ custom_variable }}"
