|-

  ---
  - name: Loop (for each) over an array in JavaScript
    hosts: localhost
    gather_facts: false

    vars:
      array_to_loop: ["item1", "item2", "item3"]

    tasks:
      - name: Debug each item in the array
        debug:
          msg: "{{ item }}"
        loop: "{{ array_to_loop }}"
