|-
  ---
  - hosts: localhost
    tasks:
      - name: Delete an exported environment variable
        shell: |
          unset {{ variable_name }}
        vars:
          variable_name: "{{ target_variable }}"
