answer: |-
  ---
  - name: Get process ID to kill a nohup process
    hosts: all
    tasks:
      - name: Get process ID of a nohup process
        shell: ps aux | grep 'nohup process_name' | grep -v grep | awk '{print $2}'
        register: process_id

      - name: Kill the nohup process
        shell: kill -9 {{ process_id.stdout }}
        when: process_id.stdout != ""
